---
title: "#OneChippewa"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: chippewalevy@gmail.com
description: "#OneChippewa is a service of the parents and residents of Doylestown that provides
  insights into the Chippewa Local School district"
author: "#OneChippewa"
twitter_username: 
github_username: 
facebook_username: OurFutureIsNow
instagram_username: 
linkedin_username: 
google_analytics: G-J03SVQ1VXJ
markdown: kramdown
paginate: 3
paginate_path: "/posts/page:num/"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
theme: jekyll-theme-clean-blog
prose:
  siteurl: http://onechippewa.org
  ignore:
  - 404.md
  - index.html
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/assets"
  - "/posts"
  - ".*"
  - CNAME
  - Gemfile
  - README.md
  - links.jsonp
  - site.css
  media: media
  relativeLinks: https://onechippewa.org/links.jsonp
  metadata:
    _posts:
    - name: category
      field:
        element: hidden
        value: blog
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Title
        value: ''
    - name: background
      field:
        element: text
        label: Background Image
        value: "/assets/mainheader.png"
    _drafts:
    - name: category
      field:
        element: hidden
        value: blog
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Title
        value: ''
    - name: background
      field:
        element: text
        label: Background Image
        value: "/assets/mainheader.png"
