title:              "#OneChippewa"
email:              chippewalevy@gmail.com
description:        "#OneChippewa is a service of the Chippewa Levy Committee that provides insights into the Chippewa Local School district"
author:             "#OneChippewa"

# Social Profiles
twitter_username:   
github_username:    
facebook_username: OurFutureIsNow 
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

prose:
  rooturl: '_posts'
  siteurl: 'https://onechippewa.org'
  relativeLinks: 'https://onechippewa.org/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "background"
        field:
          element: "text"
          label: "Background Image"
          value: "/assets/mainheader.png"
